#!/bin/bash

for I in {1..25}
do
	VAR=different
	cat /usr/share/dict/words | sort -R | head -100 > $VAR/file$I-a.txt
	cp $VAR/file$I-a.txt $VAR/file$I-b.txt
	for J in {1..80}
	do
		sed -i "$((($RANDOM +1) % 200))s/.*/$(cat /usr/share/dict/words | sort -R | head -1)/" $VAR/file$I-b.txt
	done
done

